version: 2.1
description:

orbs:
  my-orb:
    orbs:
      codecov: circleci/codecov-clojure@0.0.4
    executors:
      specialthingsexecutor:
        docker:
          - image: circleci/ruby
    commands:
      dospecialthings:
        steps:
          - run: echo "We will now do special things"
    jobs:
      myjob:
        executor: specialthingsexecutor
        steps: 
          - dospecialthings
          - codecov/upload:
              path: ~/tmp/results.xml

workflows:
  main: 
    jobs:
      - my-orb/myjob
