version: 2.1
orbs:
  myorb1: my_namespace_1/greet-user@0.0.3
jobs:
  build:
    docker: 
      - image: alpine
    steps:
      - myorb1/hello:
          username: "Advait" 
          lastname: "Kukade"
          contact_no: "8793710057"
